
title: Christopher Blunt
url: 'http://www.christopherblunt.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6


#Profile information
name: Christopher Blunt
tagline: A Developer, Satellite Communications Expert, Trainer and Hacker living in Bangkok, Thailand.
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hello@christopherblunt.com
phone: +66(0)4502-1379
website: www.christopherblunt.com #do not add http://
linkedin: 'christopher-blunt-8a9b45151'
github: c-blunt
twitter: ''

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
